### ISSUE TITLE
不能在 Dockerfile 中修改 DNS

### ISSUE THREAD

**Issue by khs1994** [liufee/docker#1]
```bash
#修改dns地址
RUN echo nameserver 223.5.5.5 > /etc/resolv.conf
```
这个是无效的

**Comment by liufee** [comment]
一定是你的错觉，当然注释掉这行也没啥影响，这个是阿里云的dns服务器地址。如果你依然遇到错误，可以加qq1838889850演示给你看是没有问题的。

**Comment by khs1994** [comment]
```
FROM centos:latest
MAINTAINER liufee job@feehi.com

#修改dns地址
RUN echo nameserver 223.5.5.5 > /etc/resolv.conf
RUN cat /etc/resolv.conf
```
你只使用这个 Dcoekrfile ，你查看 build 过程就知道了

**Comment by khs1994** [comment]
也许你误解我了，我意思是

在 Dockerfile 中不支持手动的修改 DNS、host。
也就是
```
RUN echo nameserver 223.5.5.5 > /etc/resolv.conf
RUN echo 1.1.1.1 github.com > /etc/resolv.conf
```
这不能改变  `/etc/resolv.conf` `/etc/hosts`文件的内容

**Comment by liufee** [comment]
这里的作用并不是要改变容器的dns解析地址，而是在build过程中能加速构建（yum需要解析dns地址，我在中国移动网络的情况下会出错，为了解决兼容性问题而写的）。初衷：加速docker build镜像的过程，而非改变运行容器时的地址这里的作用并不是要改变容器的dns解析地址，而是在build过程中能加速构建（yum需要解析dns地址，我在中国移动网络的情况下会出错，为了解决兼容性问题而写的）。初衷：加速docker build镜像的过程，而非改变运行容器时的地址
