### ISSUE TITLE
容器中的PHP,MYSQL没有启动

### ISSUE THREAD

**Issue by lbsfei** [liufee/docker#2]
你好，
在操作“docker run -h feehi -p 80:80 ..."这一步后，发现容器里面的php,mysql全没有启动！
这个如何处理？
谢谢回复！

**Comment by liufee** [comment]
没有启动的原因，十有八九是你映射进去的目录权限，或者没有映射必要的配置文件进入容器。可以使用docker exect -it feehi /bin/bash进入后，通过/usr/local/nginx/sbin/nginx启动，然后看nginx报错。php-fpm同理
